baseURL = "https://kubilisr.github.io/"
languageCode = "en-us"
title = "Rihards Kubilis"
theme = "codex"
copyright = "Â© {year}"

# Optional params
[params]
  # Follow the Hugo date/time format reference here:
  # https://gohugo.io/functions/format/#gos-layout-string
  dateFormat = "2006-01-02"

  # Links to your social accounts, comment/uncomment as needed. Icons will be displayed for those specified.
  github = "https://github.com/wolf3d"
  linkedin = "https://www.linkedin.com/in/kubilisr/"
  instrument = "I am teaching myself to play the banjo."
  terminal = "I do some programming as a hobby in my free time."
  languages = "I also enjoy learning new languages. I have attended Norwegian BÃ¸kmÃ¥l language courses, currently learning Finnish on my own."
  music = "I listen to music too ðŸ˜Š It's mostly different kinds of alternative rock, instrumental film scores, synthwave, lately dreampop seems appealing too."
  cpu = "I am interested to become a full-time software developer in the foreseeable future."
  person = "Hi! I'm Rihards Kubilis."
  personalpage = "This is my personal website where I share what I am working on. I mostly write about the things I have learned and created."
  book = "Sometimes I enjoy reading a good book too, recently I have started to read fantasy novels from The Witcher series"

[markup]
  defaultMarkdownHandler = "goldmark"
  [markup.highlight]
    codeFences = false

  # Set to false to disallow raw HTML in markdown files
  [markup.goldmark.renderer]
      unsafe = true
# Controls the navigation
[[menu.main]]
  identifier = "home"
  name = "home"
  title = "Home"
  url = "/"
  weight = 1
[[menu.main]]
  identifier = "blog"
  name = "blog"
  title = "Blog"
  url = "/blog/"
  weight = 2
[[menu.main]]
  identifier = "about"
  name = "about"
  title = "About"
  url = "/about/"
  weight = 3
